# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c19c7a1171249fc8ff2627ee4fce76bcba520251c722ce00eb388c72a73ebd6bbc8c55f7ce1603bd55ac1481d4f0939763cfe13e84a489d6b6b62111a1896c9a

test:
  secret_key_base: eeb0e2688705ac4a83be566ce30f687d336ce4c0d286b41d643e623983c8ffbc4f0da21418798c3f1dc5d4bcc735ed608f233f594776e2c6a7082383d3187c2d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
